/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject1;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static final String SAMPLE_CASE_MESSAGE = "CPIT425";
    public static final String SAMPLE_CASE_CIPHER = "";
    public static void main(String[] args) {
        try {
            NewJDialog a =new  NewJDialog(new javax.swing.JFrame(),true)  ;  
            a.setVisible(true);       
            
        } catch (Exception e) {
            System.out.println(e);
        }
    
    }
    
}
